 services:
  # 1. Сервис Базы данных PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: MeetlyLoop_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Сервис Бэкенда
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: MeetlyLoop_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/code/src
      - ./backend/alembic:/code/alembic
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    # РЕРАН!!!
    # command: tail -f /dev/null
    command: >
      sh -c "echo 'Running Alembic migrations...' && 
         //usr/local/bin/alembic upgrade head && 
         echo 'Starting FastAPI server...' &&
         uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

  # # 3. Сервис Фронтенда
  # frontend:
  #   build: ./frontend
  #   container_name: MeetlyLoop_frontend
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - backend
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"

  # volumes:
  #   postgres_data:
  #     driver: local