"""add_DateTime_in_posts

Revision ID: a354dcab0cd2
Revises:
Create Date: 2025-08-10 00:28:39.991914

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a354dcab0cd2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("created_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "posts", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "updated_at")
    op.drop_column("posts", "created_at")
    # ### end Alembic commands ###
