"""add_theme_in_posts

Revision ID: e38de6c3621a
Revises: a354dcab0cd2
Create Date: 2025-08-10 01:59:00.057848

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e38de6c3621a"
down_revision: Union[str, Sequence[str], None] = "a354dcab0cd2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("theme", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "theme")
    # ### end Alembic commands ###
