"""password_hash -> password

Revision ID: a946d2740b7c
Revises: e1a734f4d014
Create Date: 2025-08-18 00:37:03.514155

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a946d2740b7c"
down_revision: Union[str, Sequence[str], None] = "e1a734f4d014"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.String(), nullable=True))
    op.drop_column("users", "password_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "password_hash", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("users", "password")
    # ### end Alembic commands ###
